x-env: &env
  environment:
    - DB_NAME=${DB_NAME}
    - DB_USERNAME=${DB_USERNAME}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_HOST=${DB_HOST}
    - PORT=${API_PORT}

version: "3.5"
services:
  api:
    image: ${DOCKER_REGISTRY:-}api${DEPLOY_TAG:-}
    restart: always
    build:
      context: ./api
    ports:
      - "3001:3001"
    env_file:
      - .env